import os
import requests
from github import Github, GithubException
from dotenv import load_dotenv

load_dotenv()

def get_github_client(access_token=None):
    """Get GitHub client with token"""
    token = access_token or os.getenv("GITHUB_ACCESS_TOKEN")
    if not token:
        # For demo, use a temporary token approach
        return None
    return Github(token)

def exchange_code_for_token(code):
    """Exchange OAuth code for access token"""
    client_id = os.getenv("GITHUB_CLIENT_ID")
    client_secret = os.getenv("GITHUB_CLIENT_SECRET")
    
    response = requests.post(
        "https://github.com/login/oauth/access_token",
        json={
            "client_id": client_id,
            "client_secret": client_secret,
            "code": code
        },
        headers={"Accept": "application/json"}
    )
    
    if response.status_code == 200:
        return response.json().get("access_token")
    return None

def create_pull_request(repo_url, file_path, fixed_code, vulnerabilities, access_token, scan_id):
    """
    Create a branch, commit fixed code, and open a pull request
    """
    try:
        # Parse repo URL
        if "github.com/" in repo_url:
            repo_name = repo_url.split("github.com/")[-1]
            if repo_name.endswith(".git"):
                repo_name = repo_name[:-4]
        else:
            repo_name = repo_url
        
        # Initialize GitHub client
        g = Github(access_token)
        repo = g.get_repo(repo_name)
        
        # Create branch name
        branch_name = f"vibeguard/security-fix-{scan_id[:8]}"
        base_branch = repo.default_branch
        
        # Get the latest commit SHA of base branch
        base_ref = repo.get_git_ref(f"heads/{base_branch}")
        base_sha = base_ref.object.sha
        
        # Create new branch
        try:
            repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
        except GithubException:
            # Branch might exist, delete and recreate
            try:
                ref = repo.get_git_ref(f"heads/{branch_name}")
                ref.delete()
                repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
            except:
                pass
        
        # Get the current content if exists
        try:
            contents = repo.get_contents(file_path, ref=branch_name)
            # Update file
            repo.update_file(
                file_path,
                f"Security fix: Fixed {len(vulnerabilities)} vulnerabilities",
                fixed_code,
                contents.sha,
                branch=branch_name
            )
        except:
            # Create new file
            repo.create_file(
                file_path,
                f"Security fix: Fixed {len(vulnerabilities)} vulnerabilities",
                fixed_code,
                branch=branch_name
            )
        
        # Create PR description
        vuln_list = "\n".join([f"- {v.get('title')} (severity: {v.get('severity')})" for v in vulnerabilities[:5]])
        if len(vulnerabilities) > 5:
            vuln_list += f"\n- ... and {len(vulnerabilities) - 5} more issues"
        
        pr_body = f"""## 🔒 Security fixes by VibeGuard

This PR automatically fixes security vulnerabilities found in your code.

### Vulnerabilities Fixed:
{vuln_list}

### Changes Made:
- All critical/high severity issues patched
- Security best practices applied
- Added input validation where needed
- Removed hardcoded secrets

### Next Steps:
1. Review the changes
2. Test your application
3. Merge this PR

---
*Auto-generated by VibeGuard - Security for vibe coders*
"""
        
        # Create pull request
        pr = repo.create_pull(
            title=f"[VibeGuard] Security fix: {len(vulnerabilities)} vulnerabilities patched",
            body=pr_body,
            head=branch_name,
            base=base_branch
        )
        
        return {
            "success": True,
            "pr_url": pr.html_url,
            "pr_number": pr.number,
            "branch_name": branch_name
        }
        
    except GithubException as e:
        return {
            "success": False,
            "error": f"GitHub API error: {e.data.get('message', str(e))}"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }
